exclude: "docs|.git"
default_stages: [pre-commit]
fail_fast: true

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-merge-conflict
          - id: check-executables-have-shebangs
          - id: check-added-large-files
            args: ["--maxkb=500"]

    - repo: https://github.com/adrienverge/yamllint/
      rev: v1.37.1
      hooks:
          - id: yamllint

    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.10.0.1
      hooks:
          - id: shellcheck
            args: ["-x", "--exclude=SC1071,SC1090,SC1091,SC2155"]
