# btop configuration
# https://github.com/aristocratos/btop

# Theme
theme = "default"
# Refresh rate in seconds
refresh = 1
# Show cpu temperature
cpu_temp = true
# Use unicode box drawing
unicode = true
