#!/usr/bin/env bash

DOTFILES_TOTAL_STEPS="${DOTFILES_TOTAL_STEPS:-7}"
DOTFILES_CURRENT_STEP="${DOTFILES_CURRENT_STEP:-0}"
DOTFILES_PREVIEW_LINES="${DOTFILES_PREVIEW_LINES:-5}"

DOTFILES_SYM_PENDING="${DOTFILES_SYM_PENDING:-…}"
DOTFILES_SYM_SUCCESS="${DOTFILES_SYM_SUCCESS:-✓}"
DOTFILES_SYM_ERROR="${DOTFILES_SYM_ERROR:-✗}"

DOTFILES_COLOR_STEP="${DOTFILES_COLOR_STEP:-$'\033[38;5;220m'}"
DOTFILES_COLOR_TITLE="${DOTFILES_COLOR_TITLE:-$'\033[1;36m'}"
DOTFILES_COLOR_PREVIEW="${DOTFILES_COLOR_PREVIEW:-$'\033[2;37m'}"
DOTFILES_COLOR_INFO="${DOTFILES_COLOR_INFO:-$'\033[1;34m'}"
DOTFILES_COLOR_WARNING="${DOTFILES_COLOR_WARNING:-$'\033[1;33m'}"
DOTFILES_COLOR_SUCCESS="${DOTFILES_COLOR_SUCCESS:-$'\033[1;32m'}"
DOTFILES_COLOR_ERROR="${DOTFILES_COLOR_ERROR:-$'\033[1;31m'}"
DOTFILES_COLOR_RESET="${DOTFILES_COLOR_RESET:-$'\033[0m'}"
