# vim: foldmethod=marker
# Oh-My-Zsh {{{1

export ZSH="${HOME}/.oh-my-zsh"
export ZSH_CUSTOM="${ZSH}/custom"
export ZSH_COMPDUMP=$ZSH/cache/.zcompdump-$HOST
export XDG_CONFIG_HOME="${HOME}/.config"

plugins=(
    aws
    colored-man-pages
    docker
    docker-compose
    F-Sy-H
    fzf-tab # fzf-tab should be the last plugin to bind "^I"
    git
    helm
    you-should-use
    sudo
    zsh-autosuggestions
    zsh-direnv
)

# Use case-sensitive completion
CASE_SENSITIVE="true"

# Fix slow paste
DISABLE_MAGIC_FUNCTIONS=true

# Workaround for https://github.com/zsh-users/zsh-completions/issues/603
if [[ -d "${ZSH_CUSTOM}/plugins/zsh-completions/src" ]]; then
  fpath+="${ZSH_CUSTOM}/plugins/zsh-completions/src"
fi

# }}}

# Load oh-my-zsh
source $ZSH/oh-my-zsh.sh

# ZSH {{{1

# Apply sensisble zsh settings
source $HOME/.zshopt

# Bind C+Space to accept the current suggestion
bindkey '^ ' autosuggest-accept

# Set the default umask
umask 022

# NOTE: This code is commented out because:
#   - Modifies the keyboard configuration
#   - Generates a lot of latency
# TODO: Pending to remove
# # OSTYPE specific settings
# case "${OSTYPE}" in
#     linux*)
#         if (( $+commands[setxkbmap] )); then
#             setxkbmap -option caps:escape_shifted_capslock
#             setxkbmap -option altwin:swap_lalt_lwin
#         fi
#         ;;
#     *) ;;
# esac

# # Set Spanish keyboard layout by default
# setxkbmap -layout es
# setxkbmap -option

# Source files {{{2
# Load aliases
source $ZSH_CUSTOM/aliases.zsh

# Apply FZF configuration
source $XDG_CONFIG_HOME/fzf/fzf.zsh

# Completion {{{2

# set descriptions format to enable group support
zstyle ':completion:*:descriptions' format '[%d]'

# disable sort when completing `git checkout`
zstyle ':completion:*:git-checkout:*' sort false

# Only display targets tag for make command completion
zstyle ':completion:*:*:make::' tag-order 'targets variables'

# give a preview of commandline arguments when completing `kill`
zstyle ':completion:*:*:*:*:processes' command "ps -u $USER -o pid,user,comm -w -w"

# Other {{{2

# disable highlighting of pasted text
zle_highlight=('paste:none')

# Reload the completions (uncomment if zsh-completions don't work)
# autoload -U compinit && compinit

export STARSHIP_CONFIG="${XDG_CONFIG_HOME}/starship/starship.toml"
eval "$(starship init zsh)"