# vim: foldmethod=marker
# Oh-My-Zsh {{{1

# Load zsh plugins
plugins=(
    F-Sy-H # alternative to zsh-users/zsh-syntax-highlighting
    colored-man-pages # Adds color to man pages
    sudo  # To toggle with ESC the sudo usage
    fzf-tab # FZF integration for tab completion
    zsh-autosuggestions # Zsh plugin for fish-like autosuggestions
    # zoxide
)

# Load oh-my-zsh
source "${ZSH}/oh-my-zsh.sh"

# Apply sensisble zsh settings
source $HOME/.zshopt

# Load secrets
source $HOME/.secrets/common

# Source files {{{2
# Load aliases
source "$ZSH_CUSTOM/aliases.zsh"

# Apply styles configuration
source "$ZSH_CUSTOM/styles.zsh"

# Load domain-specific helper functions from symlinked custom path.
for zsh_function_file in "$ZSH_CUSTOM/functions"/*.zsh(N); do
    source "$zsh_function_file"
done

# Initialize starship in zsh
eval "$(starship init zsh)"

# Make nvm available in the terminal
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
